export const setUser = user => ({ type: 'SET_USER', user })
export const receiveEvents = events => ({ type: 'RECEIVE_EVENTS', payload: events })
export const receiveEvent = event => ({ type: 'RECEIVE_EVENT', payload: event })
export const newEvent = event => ({ type: 'NEW_EVENT' })
export const addEvent = event => ({ type: 'ADD_EVENT', event })
export const editEvent = event => ({ type: 'EDIT_EVENT', event })
export const deleteEvent = eventId => ({ type: 'DELETE_EVENT', eventId })
export const makeReservation = reservation => ({ type: 'MAKE_RESERVATION', payload: reservation })
export const receiveReservations = reservations => ({ type: 'RECEIVE_RESERVATIONS', payload: reservations })
export const deleteReservation = reservationId => ({ type: 'DELETE_RESERVATION', reservationId })